---
- name: Check the status of the OpenShift 4 cluster
  hosts: localhost
  vars:
    ocp_username: ""
    ocp_password: ""
    ocp_api_url: ""
    mail_host: ""
    mail_port: ""
    mail_username: ""
    mail_password: ""
    mail_to: ""
    mail_cc: ""
    mail_sender: ""

  tasks:
    - name: Set up login credentials
      k8s_auth:
        validate_certs: false
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
        host: "{{ ocp_api_url }}"
      register: k8s_auth_results
      no_log: true      

    - name: Login into cluster
      shell: |
        oc login --token {{ k8s_auth_results.openshift_auth.api_key }} {{ k8s_auth_results.openshift_auth.host }} --insecure-skip-tls-verify
      no_log: true

    - name: Verify the connection to the cluster
      k8s_info:
        kind: ClusterVersion
        name: version
      register: k8s_version
      ignore_errors: true

    - name: Checks the status of cluster nodes
      k8s_info:
        kind: Node
      register: k8s_nodes
      ignore_errors: true

    - name: Get Openshift node names
      command: oc get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
      register: oc_output
      changed_when: false

    - name: Controls the available space on Openshift nodes
      shell: oc debug nodes/{{ item }} -- df -h --output=avail /
      register: df_output
      changed_when: false
      loop: "{{ oc_output.stdout_lines }}"

    - name: Extract the available space from the results
      set_fact:
         available_space_nodes: "{{ available_space_nodes | default([]) + [(item.stdout | split('\n'))[1] | replace(' ', '') | replace('G', '')] }}"
      loop: "{{ df_output.results }}"
      when:
        - item.rc == 0
        - item.stdout_lines | length >= 2

    - name: Set threshold value for available space
      set_fact:
        threshold: 20  # Imposta il valore di soglia desiderato (in GB)

    - name: Check available space on nodes
      set_fact:
        space_check_failed: "{{ available_space_nodes is defined and available_space_nodes | map('int') | min < threshold }}"        

    - name: Check the status of OpenShift services
      k8s_info:
        kind: Pod
        field_selectors:
          - status.phase!=Running
          - status.phase!=Completed
          - status.phase!=Succeeded
      register: k8s_pods
      ignore_errors: true

    - name: Check the status of cluster operators
      k8s_info:
        kind: ClusterOperator
        api_version: config.openshift.io/v1
      register: k8s_cluster_operators
      ignore_errors: true

    - name: Check the status of CephBlockPool in ODF
      k8s_info:
        kind: CephBlockPool
        api_version: ceph.rook.io/v1
      register: k8s_ceph_status
      ignore_errors: true

    - name: Check the status of Ceph in ODF
      k8s_info:
        kind: Pod
        api_version: v1
        namespace: openshift-storage
        label_selectors: "app=rook-ceph-operator"
      register: k8s_ceph_operator_pods
      ignore_errors: true

    - name: Run Ceph status check in ODF
      shell:
        cmd: oc exec -n openshift-storage -c rook-ceph-operator "{{ item }}" -- sh -c "ceph status --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring"
      register: ceph_status
      with_items: "{{ k8s_ceph_operator_pods.resources | json_query('[].metadata.name') }}"
      ignore_errors: true

    - name: Run the available space check in Ceph ODF
      shell:
        cmd: oc exec -n openshift-storage -c rook-ceph-operator "{{ item }}" -- sh -c "ceph df --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring"
      register: ceph_df
      with_items: "{{ k8s_ceph_operator_pods.resources | json_query('[].metadata.name') }}"
      ignore_errors: true

    - name: Extract the available space in Ceph ODF
      set_fact:
          available_space_ceph: "{{ ceph_df.results[0].stdout_lines | join('\n') | regex_findall('TOTAL\\s+\\d+\\s+GiB\\s+(\\d+\\s+GiB)') | first | replace(' GiB', '') }}"
      when: ceph_df is defined

    - name: Define the variable 'checks' based on the results
      set_fact:
        checks: []

    - name: Add connection check results to the cluster
      set_fact:
        checks: "{{ checks + [{'name': 'Verifies the connection to the cluster', 'status': 'failed' if (k8s_version.resources | regex_search('\\s*Cluster version is') is none) else 'passed'}] }}"
      when: k8s_version is defined

    - name: Add the results of cluster node checks
      set_fact:
        checks: "{{ checks + [{'name': 'Verifies the status of the cluster nodes', 'status': 'failed' if k8s_nodes.rc is defined and k8s_nodes.rc != 0 else 'passed'}] }}"
      when: k8s_version is defined      

    - name: Add the results of OpenShift service checks.
      set_fact:
        checks: "{{ checks + [{'name': 'Verifies the status of OpenShift services', 'status': 'failed' if k8s_pods.rc is defined and k8s_pods.rc != 0 else 'passed'}] }}"
      when: k8s_pods is defined

    - name: Add cluster operator check results
      set_fact:
        checks: "{{ checks + [{'name': 'Verifies the status of cluster operators', 'status': 'failed' if k8s_cluster_operators.rc is defined and k8s_cluster_operators.rc != 0 else 'passed'}] }}"
      when: k8s_cluster_operators is defined

    - name: Add the results of CephBlockPool status checks in ODF
      set_fact:
        checks: "{{ checks + [{'name': 'Verifies the status of CephBlockPool in ODF', 'status': 'failed' if k8s_ceph_status.rc is defined and k8s_ceph_status.rc != 0 else 'passed'}] }}"
      when: k8s_ceph_status is defined

    - name: Add results of Ceph status checks in ODF
      set_fact:
        checks: "{{ checks + [{'name': 'Checks the status of Ceph in ODF', 'status': 'failed' if (ceph_status.results | selectattr('stdout_lines') | regex_search('\\s*HEALTH_OK') is none) else 'passed'}] }}"
      when: ceph_status is defined

    - name: Add the result of checking the available space in Ceph ODF
      set_fact:
        checks: "{{ checks + [{'name': 'Checks the available space in Ceph ODF', 'status': 'failed' if (available_space_ceph is defined and available_space_ceph | int < 200) else 'passed'}] }}"
      when: available_space_ceph is defined

    - name: Add the result of checking the available space on the nodes
      set_fact:
        checks: "{{ checks + [{'name': 'Checks the available space on nodes', 'status': 'failed' if space_check_failed else 'passed'}] }}"
      when: available_space_nodes is defined

    - name: Create output directory if it doesn't exist
      file:
        path: output
        state: directory

    - name: Genera output CSV
      template:
        src: templates/output.j2
        dest: output/output.csv
      when: checks is defined and checks | length > 0
      ignore_errors: true

    - name: Genera output HTML
      register: generate_output_html
      template:
        src: templates/template.html.j2
        dest: output/output.html
      when: checks is defined and checks | length > 0

    - name: Send the output as an HTML email
      mail:
        host: "{{ mail_host }}"
        port: "{{ mail_port }}"
        username: "{{ mail_username }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        cc: "{{ mail_cc }}"
        sender: "{{ mail_sender }}"
        subject: "OpenShift State Control Report"
        body: "{{ lookup('file', 'output/output.html') }}"
        subtype: html
        charset: utf8        
      when: checks is defined and checks | selectattr('status', 'eq', 'failed') | list | length > 0 and mail_host is defined
