- name: Playbook Site Check
  hosts: localhost

  vars:
    site_urls:
      - site1.example.com
      - site2.example.com
      - site3.example.com
    mail_host: "{{ lookup('env', 'MAIL_HOST') }}"
    mail_port: "{{ lookup('env', 'MAIL_PORT') }}"
    mail_username: "{{ lookup('env', 'MAIL_USERNAME') }}"
    mail_password: "{{ lookup('env', 'MAIL_PASSWORD') }}"
    mail_to: "{{ lookup('env', 'MAIL_TO') }}"
    mail_cc: "{{ lookup('env', 'MAIL_CC') }}"
    mail_sender: "{{ lookup('env', 'MAIL_SENDER') }}"

  collections:
    - community.general

  tasks:

    - name: Health, readiness and info check
      ansible.builtin.uri:
        url: 'https://{{ item }}'
        status_code: 200
        return_content: no
      ignore_errors: yes
      retries: 3
      delay: 30
      register: result
      until: result.status == 200
      with_items: "{{ site_urls }}"

    - name: Parse Results
      ansible.builtin.set_fact:
        site_statuses: "{{ site_statuses | default([]) + [ {'site': item.item, 'status_code': item.status} ] }}"
      loop: "{{ result.results }}"

    - name: Print Results
      ansible.builtin.debug:
        msg: "{{ site_statuses }}"

    - name: Create output directory if it doesn't exist
      ansible.builtin.file:
        path: output
        state: directory

    - name: Generate HTML Report
      ansible.builtin.template:
        src: templates/report_template.html
        dest: output/health_check_report.html

    - name: Send the output as an HTML email
      community.general.mail:
        host: "{{ mail_host }}"
        port: "{{ mail_port }}"
        username: "{{ mail_username }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        cc: "{{ mail_cc }}"
        sender: "{{ mail_sender }}"
        subject: "Site Status Monitoring Report"
        body: "{{ lookup('file', 'output/health_check_report.html') }}"
        subtype: html
        charset: utf8
      when: site_statuses | rejectattr('status_code', 'eq', 200) | list | length > 0
