---
- name: Configura static host entry per SNO su libvirt
  hosts: lab
  become: true
  vars:
    sno_name: sno2
    sno_mac: "52:54:00:6b:56:45"
    sno_domain: ocp4.lab.filice.eu
    sno_ip: "192.168.100.12"
    network_name: baremetal
    dnsmasq_conf: /etc/NetworkManager/dnsmasq.d/openshift.conf
    ocp_auth: &ocp_auth
      host: "{{ ocp_api_url }}"
      username: "{{ ocp_username }}"
      password: "{{ ocp_password }}"
      validate_certs: false

  tasks:    

    - name: Set up login credentials (OpenShift)
      redhat.openshift.openshift_auth:
        <<: *ocp_auth
        state: present
      register: k8s_auth_results  

    - name: Login into cluster
      ansible.builtin.shell: |
        oc login --token {{ k8s_auth_results.openshift_auth.api_key }} {{ k8s_auth_results.openshift_auth.host }} --insecure-skip-tls-verify

    - name: Aggiungi static host entry per {{ sno_name }}
      ansible.builtin.command:
        cmd: >
          virsh net-update {{ network_name }} add ip-dhcp-host 
          "<host mac='{{ sno_mac }}' name='{{ sno_name }}.{{ sno_domain }}' ip='{{ sno_ip }}'/>"
          --live --config
      register: update_result
      changed_when: update_result.rc == 0
      failed_when: update_result.rc != 0 and 'existing dhcp host entry' not in update_result.stderr

    - name: Verifica esistenza configurazione DNS per {{ sno_name }}
      ansible.builtin.command:
        cmd: "grep -F 'address=/api.{{ sno_name }}.{{ sno_domain }}/{{ sno_ip }}' {{ dnsmasq_conf }}"
      register: dns_check
      changed_when: false
      failed_when: false

    - name: Aggiungi configurazione DNS per {{ sno_name }}
      ansible.builtin.blockinfile:
        path: "{{ dnsmasq_conf }}"
        block: |
          address=/api.{{ sno_name }}.{{ sno_domain }}/{{ sno_ip }}
          address=/.apps.{{ sno_name }}.{{ sno_domain }}/{{ sno_ip }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ sno_name | upper }}"
      when: dns_check.rc != 0
      notify: Riavvia NetworkManager
 
    # - name: Modifica ClusterDeployment
    #   kubernetes.core.k8s:
    #     state: present
    #     kind: ClusterDeployment
    #     api_version: hive.openshift.io/v1
    #     namespace: sno2
    #     name: sno2
    #     definition:
    #       metadata:
    #         annotations:
    #           hive.openshift.io/reconcile-pause: "false"

    # - name: Modifica AgentClusterInstall
    #   kubernetes.core.k8s:
    #     state: present
    #     kind: AgentClusterInstall
    #     api_version: extensions.hive.openshift.io/v1beta1
    #     namespace: sno2
    #     name: sno2
    #     definition:
    #       spec:
    #         holdInstallation: false

  handlers:
    - name: Riavvia NetworkManager 
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
